#!/bin/bash

# Set the correct timezone
if [ -n "${TIMEZONE}" ]; then
    cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
fi

# Override capture size for Motion
if [ -n "${MOTION_PIXELS}" ]; then
    echo "Set capture size to ${MOTION_PIXELS}"
    IFS='x' read -a wxh<<< "${MOTION_PIXELS}"
    WIDTH=${wxh[0]}
    HEIGHT=${wxh[1]}
    sed -i "s/^width\s[0-9]\+/width ${WIDTH}/g" /etc/motion/motion.conf
    sed -i "s/^height\s[0-9]\+/height ${HEIGHT}/g" /etc/motion/motion.conf
fi

# Override control and video ports
if [ -n "${WEBCONTROL_PORT}" ]; then
    echo "Set webcontrol_port to ${WEBCONTROL_PORT}"
    sed -i "s/^webcontrol_port\s[0-9]\+/webcontrol_port ${WEBCONTROL_PORT}/g" /etc/motion/motion.conf
fi
if [ -n "${STREAM_PORT}" ]; then
    echo "Set stream_port to ${STREAM_PORT}"
    sed -i "s/^stream_port\s[0-9]\+/stream_port ${STREAM_PORT}/g" /etc/motion/motion.conf
fi

# Override threshold, event_gap for Motion
[ -n "${MOTION_THRESHOLD}" ] && \
    sed -i "s/^threshold\s[0-9]\+/threshold ${MOTION_THRESHOLD}/g" /etc/motion/motion.conf
[ -n "${MOTION_EVENT_GAP}" ] && \
    sed -i "s/^event_gap\s[0-9]\+/event_gap ${MOTION_EVENT_GAP}/g" /etc/motion/motion.conf

# setup IBM IOTF
if [ -n "${IOTF_ORG_ID}" ]; then
    IOTF_CONFIG_FILE="/etc/iotsample-raspberrypi/device.cfg"
    echo "#Device configuration file" >! "${IOTF_CONFIG_FILE}"
    echo "org = ${IOTF_ORG_ID}" >> "${IOTF_CONFIG_FILE}"
    echo "type = ${IOTF_DEVICE_TYPE}" >> "${IOTF_CONFIG_FILE}"
    echo "id = ${IOTF_DEVICE_ID}" >> "${IOTF_CONFIG_FILE}"
    echo "auth-method = ${IOTF_AUTH_METHOD}" >> "${IOTF_CONFIG_FILE}"
    echo "auth-token = ${IOTF_AUTH_TOKEN}" >> "${IOTF_CONFIG_FILE}"
    echo "#End of Configuration file" >> "${IOTF_CONFIG_FILE}"
fi
# and show
if [ -e "${IOTF_CONFIG_FILE}" ]; then
    cat "${IOTF_CONFIG_FILE}"
fi

# restart, check status, getdeviceid
service iot restart
service iot status
service iot getdeviceid

# Run motion (as _NOT_ daemon; runs last)
motion -n -l /dev/stderr
